site_name: 'MATSim'
site_url: 'https://matsim.org/'
repo_url: 'https://github.com/matsim-org/jekyll-website'
edit_uri: '../docs/blob/master/docs/'
remote_branch: gh-pages
copyright:

nav:
  - Overview: index.md
  - Tutorials:
      - Quick start: tutorials/general.md
  - For users:
      - 'User Guide'
      - Extensions
      - MATSim Book
      - 'Q & A'
      - Community pages
  - Developer guide:
      - Setting up your dev environment:
          - IDE configuration: devguide/ide-configuration.md
          - Java: devguide/java.md
          - Development environment: devguide/development-environment.md
          - Eclipse: devguide/eclipse/index.md
          - Eclipse JDK: devguide/eclipse/jdk.md
          - Proxy configuration: devguide/proxy-configuration.md
      - MATSim Coding Conventions:
          - Conventions: devguide/conventions.md
          - Naming conventions: devguide/naming-conventions.md
          - Configuration conventions: devguide/configuration-conventions.md
          - Data in source repository: devguide/data-in-source-repository.md
          - Documenting your code: devguide/documenting-your-code.md
          - Commit rules: devguide/commit-rules.md
          - Composition vs inheritance: devguide/prefer-composition-and-delegation-over-inheritance.md
          - Using Generics: devguide/using-generics.md
      - Builds:
          - Build a release: devguide/build-release.md
          - Custom GUI: devguide/custom-gui.md
      - API Documentation
      - Issue Tracker
      - Build Server
      - MATSim Community Pages
  - FAQ: main/faq.md
  - Community Projects: main/projects.md

theme:
  name: 'material'
  custom_dir: overrides
  #  icon:
  #    repo: fontawesome/brands/github-alt
  favicon: 'images/favicon.ico'
  logo: 'images/logo.svg'
  language: 'en'
  font:
    text: 'Source Sans Pro'
    code: 'Roboto Mono'
  features:
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

markdown_extensions:
  # Code highlighting in ``` ``` blocks
  - codehilite:
      guess_lang: true
  # Table of Contents
  - toc:
      permalink: true
  # block-styled side content
  - admonition
  # linkifies URL and email links without having to wrap them in Markdown syntax. Also, allows shortens repository issue, pull request, and commit links.
  - pymdownx.magiclink
  # Task lists (https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/)
  - pymdownx.tasklist:
      custom_checkbox: true
  # Highlight words with ==mark me==
  - pymdownx.mark
  # Adds support for deletion ~~Delete me~~ and subscript text~a\ subscript~
  - pymdownx.tilde
  # This extension is a convenience extension which includes many pymdownx extensions
  # (https://facelessuser.github.io/pymdown-extensions/extensions/extra/)
  - pymdownx.extra
  # (https://facelessuser.github.io/pymdown-extensions/extensions/details/)
  - pymdownx.details
  # Tabbed provides a syntax to easily add tabbed Markdown content.
  # https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.tabbed
  # Adds syntax for defining footnotes in Markdown documents (https://python-markdown.github.io/extensions/footnotes/)
  - footnotes
  # Adds the ability to define abbreviations
  - abbr
  # Include files in other documents like {!some/dir/in/docs/filename.md!}
  - markdown_include.include:
      base_path: docs
  # Metadata support in pages
  # (https://squidfunk.github.io/mkdocs-material/extensions/metadata/)
  - meta

extra:
  social:
    - icon: fontawesome/solid/earth-americas
      link: https://matsim.org/
      name: Website
    - icon: fontawesome/brands/github
      link: https://github.com/matsim-org
      name: GitHub

extra_css:
  - extra.css

plugins:
  - search
  - git-revision-date-localized
  - redirects:
      redirect_maps:
        'ftldns/database.md': database/index.md
        'main/presentations.md': index.md
        'main/prerequesites.md': main/prerequisites.md
